### ISSUE TITLE
Link Error on ubuntu 20.04

### ISSUE THREAD

**Issue by Hugozys** [google/fruit#120] opened 2020-07-26 02:56 UTC
I was trying to compile the simplest hello world program whose source code were given in the example:
https://github.com/google/fruit/blob/master/examples/hello_world/main.cpp

I followed the `add repository and manually install` guide stated on the wiki:
https://software.opensuse.org/download.html?project=home%3Apoletti_marco&package=libfruit

The first command I tried:
`root@fruit:~/demo# g++ -std=gnu++17 -lfruit hello.cc -o hello`
And it emits the undefined reference error:
```
/usr/bin/ld: /tmp/ccDKhdtr.o: in function `fruit::impl::MemoryPool::~MemoryPool()':
hello.cc:(.text._ZN5fruit4impl10MemoryPoolD2Ev[_ZN5fruit4impl10MemoryPoolD5Ev]+0x18): undefined reference to `fruit::impl::MemoryPool::destroy()'
/usr/bin/ld: /tmp/ccDKhdtr.o: in function `fruit::impl::SemistaticGraph<fruit::impl::TypeId, fruit::impl::NormalizedBinding>::at(fruit::impl::TypeId)':
hello.cc:(.text._ZN5fruit4impl15SemistaticGraphINS0_6TypeIdENS0_17NormalizedBindingEE2atES2_[_ZN5fruit4impl15SemistaticGraphINS0_6TypeIdENS0_17NormalizedBindingEE2atES2_]+0x32): undefined reference to `fruit::impl::SemistaticMap<fruit::impl::TypeId, fruit::impl::SemistaticGraphInternalNodeId>::at(fruit::impl::TypeId) const'
/usr/bin/ld: /tmp/ccDKhdtr.o: in function `fruit::Injector<Greeter>::Injector<>(fruit::Component<Greeter> (*)())':
hello.cc:(.text._ZN5fruit8InjectorIJ7GreeterEEC2IJEJEEEPFNS_9ComponentIJS1_EEEDpT_EDpOT0_[_ZN5fruit8InjectorIJ7GreeterEEC5IJEJEEEPFNS_9ComponentIJS1_EEEDpT_EDpOT0_]+0x114): undefined reference to `fruit::impl::InjectorStorage::InjectorStorage(fruit::impl::ComponentStorage&&, std::vector<fruit::impl::TypeId, fruit::impl::ArenaAllocator<fruit::impl::TypeId> > const&, fruit::impl::MemoryPool&)'
/usr/bin/ld: /tmp/ccDKhdtr.o: in function `std::default_delete<fruit::impl::InjectorStorage>::operator()(fruit::impl::InjectorStorage*) const':
hello.cc:(.text._ZNKSt14default_deleteIN5fruit4impl15InjectorStorageEEclEPS2_[_ZNKSt14default_deleteIN5fruit4impl15InjectorStorageEEclEPS2_]+0x22): undefined reference to `fruit::impl::InjectorStorage::~InjectorStorage()'
collect2: error: ld returned 1 exit status
```
I did a find command to look for where the shared object is located:
`find /usr -name "*fruit*"`
```
/usr/share/doc/fruit-dev
/usr/share/doc/libfruit
/usr/include/fruit
/usr/include/fruit/fruit_forward_decls.h
/usr/include/fruit/impl/fruit_internal_forward_decls.h
/usr/include/fruit/impl/fruit_assert.h
/usr/include/fruit/impl/fruit-config.h
/usr/include/fruit/impl/fruit-config-base.h
/usr/include/fruit/fruit.h
/usr/lib/x86_64-linux-gnu/libfruit.so
```
I then included ```/usr/lib/x86_64-linux-gnu/``` into search path:
```root@fruit:~/demo# g++ -std=gnu++17 -L/usr/lib/x86_64-linux-gnu -lfruit hello.cc -o hello```
Getting the same error however:
```
/usr/bin/ld: /tmp/ccsZKi7b.o: in function `fruit::impl::MemoryPool::~MemoryPool()':
hello.cc:(.text._ZN5fruit4impl10MemoryPoolD2Ev[_ZN5fruit4impl10MemoryPoolD5Ev]+0x18): undefined reference to `fruit::impl::MemoryPool::destroy()'
/usr/bin/ld: /tmp/ccsZKi7b.o: in function `fruit::impl::SemistaticGraph<fruit::impl::TypeId, fruit::impl::NormalizedBinding>::at(fruit::impl::TypeId)':
hello.cc:(.text._ZN5fruit4impl15SemistaticGraphINS0_6TypeIdENS0_17NormalizedBindingEE2atES2_[_ZN5fruit4impl15SemistaticGraphINS0_6TypeIdENS0_17NormalizedBindingEE2atES2_]+0x32): undefined reference to `fruit::impl::SemistaticMap<fruit::impl::TypeId, fruit::impl::SemistaticGraphInternalNodeId>::at(fruit::impl::TypeId) const'
/usr/bin/ld: /tmp/ccsZKi7b.o: in function `fruit::Injector<Greeter>::Injector<>(fruit::Component<Greeter> (*)())':
hello.cc:(.text._ZN5fruit8InjectorIJ7GreeterEEC2IJEJEEEPFNS_9ComponentIJS1_EEEDpT_EDpOT0_[_ZN5fruit8InjectorIJ7GreeterEEC5IJEJEEEPFNS_9ComponentIJS1_EEEDpT_EDpOT0_]+0x114): undefined reference to `fruit::impl::InjectorStorage::InjectorStorage(fruit::impl::ComponentStorage&&, std::vector<fruit::impl::TypeId, fruit::impl::ArenaAllocator<fruit::impl::TypeId> > const&, fruit::impl::MemoryPool&)'
/usr/bin/ld: /tmp/ccsZKi7b.o: in function `std::default_delete<fruit::impl::InjectorStorage>::operator()(fruit::impl::InjectorStorage*) const':
hello.cc:(.text._ZNKSt14default_deleteIN5fruit4impl15InjectorStorageEEclEPS2_[_ZNKSt14default_deleteIN5fruit4impl15InjectorStorageEEclEPS2_]+0x22): undefined reference to `fruit::impl::InjectorStorage::~InjectorStorage()'
collect2: error: ld returned 1 exit status
```
Here is my system info with `uname -a`:
```Linux fruit 5.4.0-29-generic #33-Ubuntu SMP Wed Apr 29 14:32:27 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux```

**Comment by poletti-marco** [comment] 2020-07-26 03:50
Hi, this was quite subtle: the issue is the order of the flags passed to GCC.
I can reproduce the same error with your command, but this works:

    g++ -std=gnu++17 hello.cc -o hello -lfruit

https://stackoverflow.com/questions/45135/why-does-the-order-in-which-libraries-are-linked-sometimes-cause-errors-in-gcc/409470 has some explanation of why linker flag order matters, TL;DR "Dependencies of static libraries against each other work the same - the library that needs symbols must be first, then the library that resolves the symbol.".

Closing this since I assume I found the issue, if not feel free to reopen.
Let me know if you hit any other issues using Fruit.

**Closed by poletti-marco** 2020-07-26 03:50 UTC
