### ISSUE TITLE
Errors in example using gcc 5.4.0

### ISSUE THREAD

**Issue by PedroAreias** [google/fruit#22] opened 2016-08-04 12:42 UTC
/usr/local/include/fruit/impl/storage/component_storage.defn.h:88: undefined reference to `fruit::impl::GreedyAllocatorStorage::clear()'
main.o: In function `fruit::impl::GreedyAllocatorStorage::~GreedyAllocatorStorage()':

...

main.o: In function `fruit::Injector<Greeter>::Injector(fruit::Component<Greeter>)':
/usr/local/include/fruit/impl/injector.defn.h:30: undefined reference to `fruit::impl::InjectorStorage::InjectorStorage(fruit::impl::ComponentStorage&&, std::vector<fruit::impl::TypeId, std::allocator<fruit::impl::TypeId> > const&)'
main.o: In function `std::default_delete<fruit::impl::InjectorStorage>::operator()(fruit::impl::InjectorStorage*) const':
/usr/include/c++/5/bits/unique_ptr.h:76: undefined reference to `fruit::impl::InjectorStorage::~InjectorStorage()'
main.o: In function `fruit::impl::SemistaticGraph<fruit::impl::TypeId, fruit::impl::NormalizedBindingData>::at(fruit::impl::TypeId)':
/usr/local/include/fruit/impl/data_structures/semistatic_graph.defn.h:131: undefined reference to `fruit::impl::SemistaticMap<fruit::impl::TypeId, fruit::impl::SemistaticGraphInternalNodeId>::at(fruit::impl::TypeId) const'
collect2: error: ld returned 1 exit status
make: *** [fruit] Error 1

**Comment by poletti-marco** [comment] 2016-08-05 07:36
Thanks for the report. Could you please provide some more info?
* What version of Fruit are you using?
* What commands did you execute to get that error? (cmake then make I guess? With what options?)

**Comment by poletti-marco** [comment] 2016-08-28 14:06
I cannot reproduce this issue.
I've tried with the latest version (Fruit 2.0.4) using GCC 5.4.0, building the example either via cmake+make or via a manual compile command.
If you haven't managed to find a solution yet, please let me know what you did to get this issue, without additional information I'm unable to help.

**Comment by poletti-marco** [comment] 2016-10-16 10:23
Closing since I am unable to reproduce/fix this without more information. If you can still reproduce please reopen and provide the information asked in the previous comments.

**Closed by poletti-marco** 2016-10-16 10:23 UTC

**Comment by Brandon2255p** [comment] 2018-07-05 20:40
Getting the same error

```
main.o: In function `fruit::impl::MemoryPool::~MemoryPool()':
/usr/include/fruit/impl/data_structures/memory_pool.defn.h:51: undefined reference to `fruit::impl::MemoryPool::destroy()'
main.o: In function `fruit::impl::SemistaticGraph<fruit::impl::TypeId, fruit::impl::NormalizedBinding>::at(fruit::impl::TypeId)':
/usr/include/fruit/impl/data_structures/semistatic_graph.defn.h:125: undefined reference to `fruit::impl::SemistaticMap<fruit::impl::TypeId, fruit::impl::SemistaticGraphInternalNodeId>::at(fruit::impl::TypeId) const'
main.o: In function `fruit::Injector<Logger>::Injector<>(fruit::Component<Logger> (*)())':
/usr/include/fruit/impl/injector.defn.h:37: undefined reference to `fruit::impl::InjectorStorage::InjectorStorage(fruit::impl::ComponentStorage&&, std::vector<fruit::impl::TypeId, fruit::impl::ArenaAllocator<fruit::impl::TypeId> > const&, fruit::impl::MemoryPool&)'
main.o: In function `std::default_delete<fruit::impl::InjectorStorage>::operator()(fruit::impl::InjectorStorage*) const':
/usr/include/c++/5/bits/unique_ptr.h:76: undefined reference to `fruit::impl::InjectorStorage::~InjectorStorage()'
collect2: error: ld returned 1 exit status
```

g++ version:
```
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.10' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10)
```

main.cpp
```
#include <fruit/fruit.h>
#include <iostream>
#include "Logger.h"

int main(int argc, char const *argv[])
{
    fruit::Injector<Logger> injector(getLoggerImplComponent);
    Logger* logger = injector.get<Logger*>();
    logger->Log("Hello");
    /* code */
    return 0;
}
```


Logger.h
```
#include <string>

class Logger {
public:
    virtual void Log(const std::string& s) = 0;
};

fruit::Component<Logger> getLoggerImplComponent();
```

LoggerImpl.cpp
```
#include <fruit/fruit.h>
#include <iostream>
#include "Logger.h"

class LoggerImpl : public Logger {
public:
    INJECT(LoggerImpl()) = default;

    virtual void Log(const std::string &s) override {
        std::cout << s;
    }
};

fruit::Component<Logger> getLoggerImplComponent() {
    return fruit::createComponent()
        .bind<Logger, LoggerImpl>();
}
```


$ g++ -std=c++11 -g main.cpp LoggerImpl.cpp

Using Fruit 3.1.1 installed from the apt repo

**Comment by poletti-marco** [comment] 2018-07-05 21:08
You should also link with Fruit. Just add `-lfruit` to your g++ command.

In hindsight, this is probably the same issue that @PedroAreias was reporting, so I've now added a note to the [prebuilt packages section of the wiki](https://github.com/google/fruit/wiki/install#prebuilt-packages) explaining this.
